# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: 
      - "*"  # Runs on push to any branch
  pull_request:
    branches: 
      - "*"  # Runs on pull request to any branch

permissions:
  contents: read


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
      # Step 3: Install dependencies
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install numpy
          pip install matplotlib
    - name: Run Test
      run: python app.py
